# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('dep_time', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('num_people', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_mac_address', models.CharField(max_length=255)),
                ('s_ssid', models.CharField(max_length=255)),
                ('s_created_at', models.DateTimeField()),
                ('s_rssi', models.FloatField()),
                ('s_sensor_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
    ]
