# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigIntegerField(db_column='index', primary_key=True, serialize=False)),
                ('dest', models.CharField(max_length=255)),
                ('dep_time', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('max_num', models.IntegerField()),
                ('seat_num', models.IntegerField()),
            ],
        ),
    ]
