# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigIntegerField(db_column='index', primary_key=True, serialize=False)),
                ('dest', models.CharField(max_length=255)),
                ('dep_time', models.TimeField()),
                ('dep_datetime', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('field_max_num', models.BigIntegerField(blank=True, db_column=' max_num', null=True)),
                ('seat_num', models.IntegerField()),
            ],
            options={
                'db_table': 'timetable',
                'managed': True,
            },
        ),
    ]
