# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_timetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'managed': False},
        ),
    ]
