# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='dep_datetime',
        ),
    ]
